### ISSUE TITLE
Miner doesn't show up

### ISSUE THREAD

**Issue by robtech21** [mobilegmYT/Duinotize#4]
I'm not sure if it's even doing any mining, I decided to test it by dropping the code into a fork of a [game](https://robtech21.github.io/Industry-Game/) I'm working on with a friend, the site seems to work fine but I can't tell if the miner is running or not.

**Comment by mobilegmYT** [comment]
Hey dude! MCPI Revival go brrrr. Currently reworking the code, might be done by today. Feel free to DM me for more info.

**Comment by robtech21** [comment]
> Hey dude! MCPI Revival go brrrr. Currently reworking the code, might be done by today. Feel free to DM me for more info.

Okay, thanks for letting me know. Please be sure to close the issue when you get it all fixed.
